"""empty message

Revision ID: 9eecf27b1326
Revises: 
Create Date: 2019-04-26 10:48:27.299000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eecf27b1326'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_user',
    sa.Column('userId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userName', sa.String(length=16), nullable=False),
    sa.Column('userPassword', sa.String(length=128), nullable=False),
    sa.Column('userEmail', sa.String(length=30), nullable=True),
    sa.Column('userNickname', sa.String(length=20), nullable=True),
    sa.Column('registerTime', sa.DateTime(), nullable=True),
    sa.Column('userBirth', sa.String(length=20), nullable=True),
    sa.Column('userConfirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_table('t_question',
    sa.Column('questionId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('questionTopic', sa.String(length=100), nullable=False),
    sa.Column('questionContent', sa.String(length=2000), nullable=False),
    sa.Column('questionTime', sa.DateTime(), nullable=True),
    sa.Column('questionView', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['t_user.userId'], ),
    sa.PrimaryKeyConstraint('questionId')
    )
    op.create_table('t_answer',
    sa.Column('answerId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('questionId', sa.Integer(), nullable=True),
    sa.Column('answerContent', sa.String(length=500), nullable=False),
    sa.Column('answerTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['questionId'], ['t_question.questionId'], ),
    sa.ForeignKeyConstraint(['userId'], ['t_user.userId'], ),
    sa.PrimaryKeyConstraint('answerId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_answer')
    op.drop_table('t_question')
    op.drop_table('t_user')
    # ### end Alembic commands ###
